// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6.8.2025, 13:10:47
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/plugins/**/*.{js,ts,mjs}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/composables/**/*.{js,ts,mjs}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/utils/**/*.{js,ts,mjs}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/annek/Documents/Bachelorarbeit/AccessAbilityCode/AccessAbility/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;